safe: false
auto: false
server: false
server_port: 4000

source: .
destination: ./_site
plugins: ./_plugins

future: true
lsi: false
pygments: false
title: Custom and Historic Millwork
production_url: http://customhistoric.com
markdown: kramdown
permalink: blog/:title.html
paginate: 5
exclude: ["README.md"]

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false